deply scripts

diff --git a/.github/workflows/main_api-sampleapp-dev1.yml b/.github/workflows/main_api-sampleapp-dev1.yml
--- a/.github/workflows/main_api-sampleapp-dev1.yml
+++ b/.github/workflows/main_api-sampleapp-dev1.yml
@@ -82,16 +82,28 @@ jobs:
       #     package: .
       - name: Run deployment in temporary ACI container
         run: |
+          set +e # Disable exit-on-error mode
+          echo "Creating container to deploy package"
+          
           # Create the temporary container with .NET and Azure CLI
           az container create \
             --name deploy-container \
             --image mcr.microsoft.com/dotnet/aspnet:9.0 \
             --resource-group $AZURE_RESOURCE_GROUP \
             --vnet vnet-dev1 \
-            --subnet subnet-api-dev1 \
+            --subnet subnet-aci-dev1 \
             --environment-variables AZURE_WEBAPP_NAME=$AZURE_WEBAPP_NAME AZURE_RESOURCE_GROUP=$AZURE_RESOURCE_GROUP \
-            --command-line "bash -c 'apt-get update && apt-get install -y curl gnupg ca-certificates lsb-release apt-transport-https && curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && curl -sSL https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-9.0.100-linux-x64-binaries && dotnet --version && az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src /workspace/sampleapp-artifact.zip'"
+            --command-line "bash -c 'apt-get update && apt-get install -y curl gnupg ca-certificates lsb-release apt-transport-https && curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && curl -sSL https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-9.0.100-linux-x64-binaries && dotnet --version && az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src /workspace/sampleappgateway-artifact.zip'"
+          
+          # Check the container creation status (for debugging purposes)
+          if [ $? -ne 0 ]; then
+            echo "Error: Container creation failed. Cleaning up..."
+            az container delete --name deploy-container --resource-group rg-dev1 --yes --no-wait
+            exit 1
+          fi
 
       - name: Clean up ACI container
+        if: failure() || success() # Ensure cleanup happens whether the previous step fails or succeeds
         run: |
+          echo "Cleaning up ACI container..."
           az container delete --name deploy-container --resource-group rg-dev1 --yes --no-wait
